---
title: "Figure 6"
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "docs") })

---


```{r include = FALSE}
rm(list = ls())

library(ComplexHeatmap)
library(circlize)
library(Seurat)
library(ggplot2)
library(ggrepel)
library(dplyr)
library(plotly)
library(cowplot)
library(tidyr)
library(corrplot)
library('org.Hs.eg.db')
library(ReactomePA)
library("AnnotationDbi")
library("clusterProfiler")
library(GGally)
library("Runuran")
library(tidyverse)

options(ggrepel.max.overlaps = Inf) 
```

Load cohort annotation file and Epithelial cells Seurat object

```{r include=F, eval=T}

anno <- read.table("files/Endometriosis single cell cohort - Cohort.updated.Jan.06.2022.csv", sep = ",", header = TRUE, stringsAsFactors = F)
anno = anno[!anno$Status == "Fail", 1:22]
anno$Major.Class[anno$Major.Class == "Extra-ovarian endometriosis"] <- "Endometriosis"
.anno = anno[!anno$Patient.No. == "",]
.anno$SampleName[33:49] <- paste0(.anno$SampleName[33:49], "_", .anno$Index[33:49])
.anno = .anno[1:49,]
rownames(.anno) <- .anno$SampleName
.anno$Major.Class[.anno$SampleName == "BEME228_A4"] <- "Endometriosis"
.anno
dim(.anno)


classsification = read.delim("files/Endometriosis single cell cohort - CompareSurgical-rm-Endometrioma_updated_feb_02_22.csv", sep = ",", stringsAsFactors = F)
classsification = classsification[classsification$Depth.KW == classsification$Depth.MS,]
classsification = classsification[classsification$Pathologic.classification. != "No endometriosis detected",] 
classsification = classsification[-which(classsification$SampleName == "BEME228_A5"),]


anno.class = .anno[which(.anno$SampleName %in% classsification$SampleName),]
anno.class = anno.class[-which(anno.class$SampleName %in% c("S19259_BC", "S19286_CF")),]
anno.class$CominedSurgical = classsification$Depth.KW[match(anno.class$SampleName, classsification$SampleName)]
anno.class[, c("Patient.No.", "SampleName", "CominedSurgical")]


anno.class$CominedSurgical[anno.class$SampleName == "S19225_D"] <- "Deep"

anno.class$Fibrosis[anno.class$SampleName == "S19286_AE"] <- "moderate"

anno.class$CominedSurgical[anno.class$SampleName == "S19286_H"] <- "Deep"

anno.class$Hemorrhage[anno.class$SampleName == "BEME228_A4"] <- "none"
anno.class$Fibrosis[anno.class$SampleName == "BEME228_A4"] <- "mild"

anno.class$Hemorrhage[anno.class$SampleName == "BEME228_A5"] <- "none"
anno.class$Fibrosis[anno.class$SampleName == "BEME228_A5"] <- "mild"

anno.class$CominedSurgical[anno.class$SampleName == "BEME209_B3"] <- "Superficial"
anno.class$Hemorrhage[anno.class$SampleName == "BEME209_B3"] <- "none"
anno.class$Fibrosis[anno.class$SampleName == "BEME209_B3"] <- "moderate"

anno.class$Hemorrhage[anno.class$SampleName == "BEME207_B7"] <- "mild"
anno.class$Fibrosis[anno.class$SampleName == "BEME207_B7"] <- "moderate"

anno.class$Hemorrhage[anno.class$SampleName == "BEME013_C1"] <- "none"
anno.class$Fibrosis[anno.class$SampleName == "BEME013_C1"] <- "moderate"

anno.class$Hemorrhage[anno.class$SampleName == "BEME008_C3"] <- "none"
anno.class$Fibrosis[anno.class$SampleName == "BEME008_C3"] <- "mild"

anno.class$Hemorrhage[anno.class$SampleName == "BEME008_C4"] <- "none"
anno.class$Fibrosis[anno.class$SampleName == "BEME008_C4"] <- "moderate"

anno.class$Hemorrhage[anno.class$SampleName == "BEME008_C6"] <- "none"
anno.class$Fibrosis[anno.class$SampleName == "BEME008_C6"] <- "mild"

anno.class$Hemorrhage[anno.class$SampleName == "BEME008_C7"] <- "none"
anno.class$Fibrosis[anno.class$SampleName == "BEME008_C7"] <- "mild"

levels(anno.class$Fibrosis) <- c(levels(anno.class$Fibrosis), "Yes", "No")
anno.class$Fibrosis[which(anno.class$Fibrosis == "none")] <- "No"
anno.class$Fibrosis[which(anno.class$Fibrosis != "No")] <- "Yes"

levels(anno.class$Hemorrhage) <- c(levels(anno.class$Hemorrhage), "Yes", "No")
anno.class$Hemorrhage[which(anno.class$Hemorrhage == "none")] <- "No"
anno.class$Hemorrhage[which(anno.class$Hemorrhage != "No")] <- "Yes"

rownames(anno.class) <- 1:nrow(anno.class)
anno.class <- droplevels(anno.class)
anno.class.obs = anno.class[,c("Patient.No.", "SampleName", "CominedSurgical", "Hemorrhage", "Fresh.Frozen", "Fibrosis")]

.aux.seurat = readRDS("rds/deep.superficial.samples.cells.rds")

```

## Figure 6-a

``` {r figure7D, include=T, warning=FALSE, message=F, fig.align = 'center', fig.width = 5, fig.height=6}

anno.class = anno.class.obs

############
class = "Endometrial-type Epithelium"
sel.sc = readRDS("rds/EnEpi_cells.rds")

prop.cells <- data.frame(table(sel.sc@meta.data$active.cluster))
prop.cells$Var1 <- factor(prop.cells$Var1, levels = prop.cells$Var1)
ggplot(prop.cells, aes(Var1, Freq)) +
  geom_col() +
  theme_minimal(base_size = 15) +
  geom_text(aes(label=Freq), position=position_dodge(width=0.9), vjust=-0.25) +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank()) +
  labs(y = "Number of Cells")

prop.cells <- data.frame(table(sel.sc@meta.data$Major.Class))
prop.cells$Var1 <- factor(prop.cells$Var1, levels = prop.cells$Var1)
ggplot(prop.cells, aes(Var1, Freq)) +
  geom_col() +
  theme_minimal(base_size = 15) +
  geom_text(aes(label=Freq), position=position_dodge(width=0.9), vjust=-0.25) +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank()) +
  labs(y = "Number of Cells")


.sel.sc = subset(sel.sc, subset = SampleName %in% unique(anno.class$SampleName))


prop.cells <- data.frame(table(.sel.sc@meta.data$active.cluster))
prop.cells$Var1 <- factor(prop.cells$Var1, levels = prop.cells$Var1)
ggplot(prop.cells, aes(Var1, Freq)) +
  geom_col() +
  theme_minimal(base_size = 15) +
  geom_text(aes(label=Freq), position=position_dodge(width=0.9), vjust=-0.25) +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank()) +
  labs(y = "Number of Cells")

prop.cells <- data.frame(table(.sel.sc@meta.data$Major.Class))
prop.cells$Var1 <- factor(prop.cells$Var1, levels = prop.cells$Var1)
ggplot(prop.cells, aes(Var1, Freq)) +
  geom_col() +
  theme_minimal(base_size = 15) +
  geom_text(aes(label=Freq), position=position_dodge(width=0.9), vjust=-0.25) +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank()) +
  labs(y = "Number of Cells")

.sel.sc@meta.data$Surgical = NA

for (i in 1:nrow(anno.class)) {
  sample = anno.class$SampleName[i]
  .sel.sc@meta.data$Surgical[.sel.sc@meta.data$SampleName == sample] <- anno.class$CominedSurgical[i]
}


Idents(object = .sel.sc) <- .sel.sc@meta.data$Surgical

DEG.res <- FindAllMarkers(.sel.sc, test.use = "MAST")

fc.p = 0.9
pv.p = 0.05
DEG.res$STATUS = "NOT.SIG"
DEG.res[DEG.res$avg_log2FC < -fc.p & DEG.res$p_val_adj < pv.p, ]$STATUS = "Down"
DEG.res[DEG.res$avg_log2FC > fc.p & DEG.res$p_val_adj < pv.p, ]$STATUS = "Up"

feature = "Surgical"
c = "Deep"

markers.filt = DEG.res[DEG.res$cluster == c,]
nDEG = nrow(markers.filt)
genes = markers.filt$gene[markers.filt$cluster == c & markers.filt$STATUS != "NOT.SIG"]

pv <- ggplot(markers.filt, aes(x = avg_log2FC, y = -log10(p_val_adj))) +
  geom_point(aes(color = STATUS), cex = 1.45) +
  scale_color_manual(values = c("darkgreen", "grey", "red")) +
  ylim(0, 65) +
  theme_bw(base_size = 15) + 
  theme(legend.position = "bottom",
        plot.title = element_text(hjust = 0.5)) +
  geom_text_repel(
    data          = subset(markers.filt, STATUS == "Up"),
    aes(label = markers.filt$gene[which(markers.filt$gene %in% genes  & markers.filt$STATUS %in% "Up")]),
    segment.size  = 0.4,
    direction     = "y",
    segment.color = "grey50",
    hjust         = 0
  ) +
  geom_text_repel(
    data          = subset(markers.filt, STATUS == "Down"),
    aes(label = markers.filt$gene[which(markers.filt$gene %in% genes & markers.filt$STATUS %in% "Down")]),
    segment.size  = 0.4,
    direction     = "y",
    segment.color = "grey50",
    hjust         = 1
  ) +
  geom_hline(yintercept = -log10(pv.p), linetype="dotted", color = "black", size= 0.5) +
  geom_vline(xintercept = -fc.p, linetype="dotted", color = "black", size= 0.5) +
  geom_vline(xintercept = fc.p, linetype="dotted", color = "black", size= 0.5) +
  labs(title = paste0(feature, " : ", c, " (n=", nDEG, ") FC: ", fc.p, " pval = ", pv.p))
pv

```


## Figure 6-b


```{r figure7E, include=F, eval=T}
gs.ephi <- lapply(unique(DEG.res$cluster), function(x) {
  print(x)
  
  clu <- DEG.res[DEG.res$cluster == x,]
  clu <- clu[clu$p_val_adj < 0.05 & clu$avg_log2FC > 0,]
  
  
  symbols = clu$gene
  IDs = mapIds(org.Hs.eg.db, symbols, 'ENTREZID', 'SYMBOL')
  
  return(IDs)
  
})

names(gs.ephi) <- as.character(unique(DEG.res$cluster))
res <- compareCluster(gs.ephi, fun="enrichPathway")

dp <- clusterProfiler::dotplot(res, showCategory=10) 
```


```{r figure7E-p2, include=T, warning=F, message=F, fig.width = 5, fig.height=10, fig.align='center'}
res <- compareCluster(gs.ephi, fun="enrichPathway")

dp + RotatedAxis()

```


## Figure 6-c

``` {r include=T, warning=FALSE, message=F, fig.align = 'center', fig.width = 5, fig.height=6}

class = "Endometrial-type Stroma"
sel.sc = readRDS("rds/EnS_cells.rds")

prop.cells <- data.frame(table(sel.sc@meta.data$active.cluster))
prop.cells$Var1 <- factor(prop.cells$Var1, levels = prop.cells$Var1)
ggplot(prop.cells, aes(Var1, Freq)) +
  geom_col() +
  theme_minimal(base_size = 15) +
  geom_text(aes(label=Freq), position=position_dodge(width=0.9), vjust=-0.25) +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank()) +
  labs(y = "Number of Cells")

prop.cells <- data.frame(table(sel.sc@meta.data$Major.Class))
prop.cells$Var1 <- factor(prop.cells$Var1, levels = prop.cells$Var1)
ggplot(prop.cells, aes(Var1, Freq)) +
  geom_col() +
  theme_minimal(base_size = 15) +
  geom_text(aes(label=Freq), position=position_dodge(width=0.9), vjust=-0.25) +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank()) +
  labs(y = "Number of Cells")


.sel.sc = subset(sel.sc, subset = SampleName %in% unique(anno.class$SampleName))

prop.cells <- data.frame(table(.sel.sc@meta.data$active.cluster))
prop.cells$Var1 <- factor(prop.cells$Var1, levels = prop.cells$Var1)
ggplot(prop.cells, aes(Var1, Freq)) +
  geom_col() +
  theme_minimal(base_size = 15) +
  geom_text(aes(label=Freq), position=position_dodge(width=0.9), vjust=-0.25) +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank()) +
  labs(y = "Number of Cells")

prop.cells <- data.frame(table(.sel.sc@meta.data$Major.Class))
prop.cells$Var1 <- factor(prop.cells$Var1, levels = prop.cells$Var1)
ggplot(prop.cells, aes(Var1, Freq)) +
  geom_col() +
  theme_minimal(base_size = 15) +
  geom_text(aes(label=Freq), position=position_dodge(width=0.9), vjust=-0.25) +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank()) +
  labs(y = "Number of Cells")

.sel.sc@meta.data$Surgical = NA

for (i in 1:nrow(anno.class)) {
  sample = anno.class$SampleName[i]
  .sel.sc@meta.data$Surgical[.sel.sc@meta.data$SampleName == sample] <- anno.class$CominedSurgical[i]
}


Idents(object = .sel.sc) <- .sel.sc@meta.data$Surgical

DEG.res <- FindAllMarkers(.sel.sc, test.use = "MAST")

fc.p = 1.1
pv.p = 0.05
DEG.res$STATUS = "NOT.SIG"
DEG.res[DEG.res$avg_log2FC < -fc.p & DEG.res$p_val_adj < pv.p, ]$STATUS = "Down"
DEG.res[DEG.res$avg_log2FC > fc.p & DEG.res$p_val_adj < pv.p, ]$STATUS = "Up"

feature = "Surgical"
c = "Deep"

markers.filt = DEG.res[DEG.res$cluster == c,]
nDEG = nrow(markers.filt)
genes = markers.filt$gene[markers.filt$cluster == c & markers.filt$STATUS != "NOT.SIG"]

pv <- ggplot(markers.filt, aes(x = avg_log2FC, y = -log10(p_val_adj))) +
  geom_point(aes(color = STATUS), cex = 1.45) +
  scale_color_manual(values = c("darkgreen", "grey", "red")) +
  ylim(0, 65) +
  theme_bw(base_size = 15) + 
  theme(legend.position = "bottom",
        plot.title = element_text(hjust = 0.5)) +
  geom_text_repel(
    data          = subset(markers.filt, STATUS == "Up"),
    aes(label = markers.filt$gene[which(markers.filt$gene %in% genes  & markers.filt$STATUS %in% "Up")]),
    segment.size  = 0.4,
    direction     = "y",
    segment.color = "grey50",
    hjust         = 0
  ) +
  geom_text_repel(
    data          = subset(markers.filt, STATUS == "Down"),
    aes(label = markers.filt$gene[which(markers.filt$gene %in% genes & markers.filt$STATUS %in% "Down")]),
    segment.size  = 0.4,
    direction     = "y",
    segment.color = "grey50",
    hjust         = 1
  ) +
  geom_hline(yintercept = -log10(pv.p), linetype="dotted", color = "black", size= 0.5) +
  geom_vline(xintercept = -fc.p, linetype="dotted", color = "black", size= 0.5) +
  geom_vline(xintercept = fc.p, linetype="dotted", color = "black", size= 0.5) +
  labs(title = paste0(feature, " : ", c, " (n=", nDEG, ") FC: ", fc.p, " pval = ", pv.p))
pv


```



```{r include=F, eval=T}
gs.ephi <- lapply(unique(DEG.res$cluster), function(x) {
  print(x)
  
  clu <- DEG.res[DEG.res$cluster == x,]
  clu <- clu[clu$p_val_adj < 0.05 & clu$avg_log2FC > 0,]
  
  
  symbols = clu$gene
  IDs = mapIds(org.Hs.eg.db, symbols, 'ENTREZID', 'SYMBOL')
  
  return(IDs)
  
})

names(gs.ephi) <- as.character(unique(DEG.res$cluster))
res <- compareCluster(gs.ephi, fun="enrichPathway")

dp <- clusterProfiler::dotplot(res, showCategory=10) 

```

## Figure 6-d

```{r include=T, warning=F, message=F, fig.width = 5, fig.height=10, fig.align='center'}
res <- compareCluster(gs.ephi, fun="enrichPathway")
dp + RotatedAxis()

```


