---
title: "Main"
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "docs") })
---

### Introduction

This document contains code workflows, explaining how to perform the bioinformatics analysis described in ***Single-cell transcriptomic analysis of endometriosis***

#### Summmary abstract
A single-cell transcriptomic analysis of endometriosis, endometriomas, eutopic endometrial samples and uninvolved ovary tissues highlights cell populations characteristic of these tissue types. Transcriptional and cellular heterogeneity across tissues suggests novel therapeutic targets and biomarkers for this disease.

#### Data availability
Processed files used in the figures can be download from the following link:
[Seurat object files](https://cedars.box.com/s/1ks3eyzlpnjbrseefw3j4k7nx6p2ut02)
Primary sequencing data are available through the Gene Expression Omnibus under accession no. [GSE213216](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE213216)


#### Authors

Marcos A.S. Fonseca\*, Marcela Haro\*, Kelly N. Wright\*, Xianzhi Lin\*, Forough Abbasi, Jennifer Sun, Lourdes Hernandez, Natasha L. Orr, Jooyoon Hong, Yunhee Choi-Kuaea, Horacio M. Maluf, Bonnie L. Balzer, Aaron Fishburn, Ryan Hickey, Ilana Cass, Helen S. Goodridge, Mireille Truong, Yemin Wang, Margareta D. Pisarska, Huy Dinh, Amal EL-Naggar, David Huntsman, Michael S. Anglesio, Marc T. Goodman, Fabiola Medeiros†, Matthew Siedhoff†, Kate Lawrenson†



#### Document authors
Marcos A. S. Fonseca


